# Generated by Django 2.1 on 2026-09-23 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 23, 5, 5, 14, 886152, tzinfo=utc)),
        ),
    ]
