# Generated by Django 2.1 on 2026-09-23 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_created',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
